[workspace]

members = [
    "components/bytes-trie",
    "components/cldr-json-data-provider",
    "components/data-provider",
    "components/fs-data-provider",
    "components/icu",
    "components/icu4x",
    "components/uniset",
    "components/locale",
    "components/num-util",
    "components/pluralrules",
]
